name: deploy-to-live
on:
  push:
    branches:
      - master-source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Inspecting directory
        run: tree ./
      - name: Checking out repository
        uses: actions/checkout@v2
        with:
          path: sanchom.github.io
      - name: Inspecting directory
        run: tree ./
      - name: Pulling my custom pollen Docker image
        run: docker pull sanchom/pollen
      - name: Starting container
        run: docker run -v `pwd`:/work --name racket_container -d sanchom/pollen tail -f /dev/null
      - name: Installing latest pollen dependencies in container
        run: docker exec racket_container raco pkg install pollen-citations-mcgill
      - name: Inspecting work directory
        run: docker exec racket_container ls /work
      - name: Testing
        run: docker exec racket_container bash -c "cd /work/sanchom.github.io && raco test pollen.rkt markdown.rkt util.rkt"
      - name: Rendering
        run: docker exec racket_container bash -c "cd /work && raco pollen render -r sanchom.github.io"
      - name: Publishing to staging folder
        run: docker exec racket_container bash -c "cd /work && raco pollen publish sanchom.github.io published"
      - name: Shuting down container
        run: docker rm -f racket_container
      - name: Moving the staging folder into the repository
        run: sudo mv published sanchom.github.io
      - name: Inspecting directory
        run: tree ./
      - name: Deploying to live
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: sanchom.github.io/published
          clean: false
          dry-run: true
